#Dockerization
version: "3.9"

services:
  backend:
    build: ./backend
    container_name: chatbot-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: chatbot_db
      DB_USER: postgres
      DB_PASSWORD: postgres

  frontend:
    build: ./frontend
    container_name: chatbot-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: chatbot-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatbot_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
